### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by wusatosi** [beman-project/exemplar#27]
Hi, I am looking over the CI system and have some questions and proposals.

- What is the update to #6 ? Is there a reason that its blocked?
- Why do we spin up a docker container rather than using the built-in worker environment?
- Why is the CI is specifically configured to only trigger on the main branch?
- Are we interested in linting the code as checks? Is there a standard lint rule that we follow?
- Are we interested in auto-formatting for PRs?
- Is this still true? 

https://github.com/beman-project/exemplar/blob/d9145b52c9072a569d747547edfc7e03a1494809/.ci/docker/ubuntu.Dockerfile#L3-L4

I know a lot of these configurations are carryover-ed from https://github.com/bretbrownjr/zerocode so that some haven't been evaluated against their use in beman-project. I would happy to implement any improvements.

Action Items from discussions below + weekly sync:
- [x] Close #6
- [x] Remove main branch restriction for CI-trigger #28
- [x] Create Periodic Builds #28 
- [x] Implement #34 
- [x] Auto-format on PRs #46 
- [ ] Update to using GitHub native image instead of docker #48

**Comment by wusatosi** [comment]
Lint proposal in projects: https://github.com/beman-project/Optional26/issues/11

**Comment by bretbrownjr** [comment]
>What is the update to https://github.com/beman-project/exemplar/pull/6 ? Is there a reason that its blocked?

No reason. If you'd like to make one or more PRs to improve CI, I'll close the PR by @mguid65, assuming he doesn't.

>Why do we spin up a docker container rather than using the built-in worker environment?

It's nice to be able to locally reproduce the environment used in CI, though I'm persuadable if someone has other thoughts on this detail.

>Why is the CI is specifically configured to only trigger on the main branch?

That's probably misconfigured. We do want periodic builds on the main branch, but building commits on PR is also important.

>Are we interested in linting the code as checks? Is there a standard lint rule that we follow?

Yes. Nobody has proposed a specific lint rules that Beman projects should use. I thought I had `CMAKE_CXX_CLANG_TIDY` configured, but I must be misremembering, because `ci_tests.yml` doesn't have anything like that. We do have [warnings treated as errors in one part of the CI matrix](https://github.com/beman-project/exemplar/blob/main/.github/workflows/ci_tests.yml#L32). Suggestions are welcome on improving static analysis coverage.

>Are we interested in auto-formatting for PRs?

I am. We like to use popular industry tools, so `clang-format` would make sense.

>Is this still true?

CMake FILE_SET requires CMake 3.23. We should pick an OS with at least that version available. If we need to support an OS that doesn't support CMake 3.23, let's clarify that in the Beman standard somehow, because that would imply using fairly conservative CMake tech (3.23 is almost three years old).

**Comment by wusatosi** [comment]
> > No reason. If you'd like to make one or more PRs to improve CI, I'll close the PR by @mguid65, assuming he doesn't.
> 
> It's fine it can be closed or forked. I will not have time to work on it at the moment.

I could fork it and pick it up : )

**Comment by wusatosi** [comment]
> > What is the update to #6 ? Is there a reason that its blocked?
> 
> No reason. If you'd like to make one or more PRs to improve CI, I'll close the PR by @mguid65, assuming he doesn't.
> 
> > Why do we spin up a docker container rather than using the built-in worker environment?
> 
> It's nice to be able to locally reproduce the environment used in CI, though I'm persuadable if someone has other thoughts on this detail.
> 
> > Why is the CI is specifically configured to only trigger on the main branch?
> 
> That's probably misconfigured. We do want periodic builds on the main branch, but building commits on PR is also important.
> 
> > Are we interested in linting the code as checks? Is there a standard lint rule that we follow?
> 
> Yes. Nobody has proposed a specific lint rules that Beman projects should use. I thought I had `CMAKE_CXX_CLANG_TIDY` configured, but I must be misremembering, because `ci_tests.yml` doesn't have anything like that. We do have [warnings treated as errors in one part of the CI matrix](https://github.com/beman-project/exemplar/blob/main/.github/workflows/ci_tests.yml#L32). Suggestions are welcome on improving static analysis coverage.
> 
> > Are we interested in auto-formatting for PRs?
> 
> I am. We like to use popular industry tools, so `clang-format` would make sense.
> 
> > Is this still true?
> 
> CMake FILE_SET requires CMake 3.23. We should pick an OS with at least that version available. If we need to support an OS that doesn't support CMake 3.23, let's clarify that in the Beman standard somehow, because that would imply using fairly conservative CMake tech (3.23 is almost three years old).

What would be a good frequency for rebuilds? Nightly? Weekly?

**Comment by neatudarius** [comment]
> Why do we spin up a docker container rather than using the built-in worker environment?
> It's nice to be able to locally reproduce the environment used in CI, though I'm persuadable if someone has other thoughts on this detail.

Please also check https://github.com/beman-project/optional26/blob/main/docs/debug-ci.md. @bretbrownjr , would that be sufficient to locally test what happens on git push on local setup?

CC: @steve-downey 

Btw, I think we should see what tooling we already have in some repos (e.g. optional26), and if they are good, to promote that infrastructure to exemplar.

**Comment by wusatosi** [comment]
> > Why do we spin up a docker container rather than using the built-in worker environment?
> > It's nice to be able to locally reproduce the environment used in CI, though I'm persuadable if someone has other thoughts on this detail.
> 
> Please also check https://github.com/beman-project/optional26/blob/main/docs/debug-ci.md. @bretbrownjr , would that be sufficient to locally test what happens on git push on local setup?
> 
> CC: @steve-downey 
> 
> Btw, I think we should see what tooling we already have in some repos (e.g. optional26), and if they are good, to promote that infrastructure to exemplar.
> 
> I think we need a sync with next topics:
> - Docker support vs necto/act tool (https://github.com/beman-project/optional26/blob/main/docs/debug-ci.md)
> - Entries in matrix for CI
> 

Hi I would like to provide a pr against current CI to use the worker environment rather than docker to run tests. IMO this is better than running docker as it speeds up the CI time and integrates with GitHub Action's ecosystem a bit better. It does make the result non-reproducable, not as simple as `docker run` at least. But GitHub Action's default workers are usually pretty standard, and for most of the cases CI succeeds/ fail with non-platform specific bugs. I think having a CI that finishes in 30s is going to be more beneficial.

**Comment by camio** [comment]
> Are we interested in linting the code as checks?

I also support this. @steve-downey [spoke about using pre-commit](https://discourse.bemanproject.org/t/pre-commit-and-python-virtual-environments/165) elsewhere and I'm also a fan of this tool.

> Are we interested in auto-formatting for PRs?

I support this for exemplar. I was told from clang developers that the LLVM style gets the most attention from clang-format developers, so it is a good one to use.

>  [Using [github runner images](https://github.com/actions/runner-images/tree/main/images)] is better than running docker as it speeds up the CI time and integrates with GitHub Action's ecosystem a bit better

It also has support for Windows and Mac build environments. I've been happy using these in [stlab's libraries](https://github.com/stlab/libraries/tree/main). It's especially nice to not have to maintain scripts building docker images.

**Comment by mguid65** [comment]
If we use auto formatting, would it only apply to changes, or whole files:

The git-clang-format script allows for formatting only lines that differ:

https://clang.llvm.org/docs/ClangFormat.html#git-integration

**Comment by wusatosi** [comment]
> If we use auto formatting, would it only apply to changes, or whole files:
> 
> The git-clang-format script allows for formatting only lines that differ:
> 
> https://clang.llvm.org/docs/ClangFormat.html#git-integration

Thanks for the info! If perform clang-format check on every pr, this wouldn't matter.
